[tasks.run-test]
script = [
'cargo test',
'''
assert() {
  expected="$1"
  input="$2"

  ./target/debug/rcc "$input" > tmp.s
  cc -o tmp tmp.s
  set +e
  ./tmp
  actual="$?"
  set -e
  rm tmp.s tmp

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}

cargo build
assert 0 0
assert 42 42
assert 21 "5 + 20 - 4"
assert 23 "3 + 4 * 5"
assert 42 "90 / 2 - 3"
assert 35 "(3 + 4) * 5"
assert 15 "5 * (9 - 6)"

echo OK
'''
]
